### ISSUE TITLE
Send embedded image of color palette to bypass Discords caching

### ISSUE THREAD

**Issue by bdbch** [db2k/cordlr-palettes#2]
Example URL:
https://coolors.co/export/png/FF0000-ff0000-b30000-ffbfbf-ff8080

**Comment by ciruz** [comment]
The fix is really simple, just need to change [this](https://github.com/db2k/cordlr-palettes/blob/master/index.js#L29):

```js
message.reply('Here is your palette: https://coolors.co/' + colorString)
```

to this:

```js
message.reply('Here is your palette: https://coolors.co/' + colorString, {
    embed: {
        image: {
            url: 'https://coolors.co/export/png/' + colorString
        }
    }
})
```

![image](https://cloud.githubusercontent.com/assets/987947/23727964/89bf72ca-045a-11e7-839f-557d5ceb345d.png)

The only problem here is, that the used discord.js version in cordlr not really supports embed messages (not as **reply** and the method **message.channel.sendEmbed** doesnt exist, also you can't send an embed message with **message.channel.sendMessage** as second argument).

I updated discord.js inside cordlr for testing purpose to the latest discord.js version (11.0.0 right now) and this fix worked fine, but with the current used discord.js version, I'm pretty sure you cant send an embed message.

We really need to upgrade discord.js.

**Comment by bdbch** [comment]
I'll update Discord.js. Could you add an issue for that on the cordlr-cli repository? I'll take care of that. You can also send in a PR if you want to.

Otherwise great one! I'll implement embeds into other modules too.

**Comment by ciruz** [comment]
I did https://github.com/Devcord/cordlr-cli/issues/112.

I'll go to bed now, maybe I can make a PR tomorrow or you are faster.

**Comment by bdbch** [comment]
Discord.js is updated!

**Comment by ciruz** [comment]
I made an PR and I reported this bug to coolors.co. They said, they gonna fix this too.
